version: "3.8"

services:
  sonic_indexer:
    build: .
    container_name: sonic_indexer
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CHECKPOINT_DIR=/app/checkpoints_files
    volumes:
      - ./sonic_data:/app/sonic_data
      - ./checkpoints_files:/app/checkpoints_files
      - ./logs:/app/logs