[project]
name = "sonic-data-indexer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3==1.35.99",
    "dotenv>=0.9.9",
    "polars>=1.27.1",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
